### ISSUE TITLE
Excellent!

### ISSUE THREAD

**Issue by FGRibreau** [EulerianTechnologies/eredis#1]
Merci pour cette release @guillaumef!

Eredis sera partagé dans notre prochaine [RedisWeekly](https://redisweekly.com) demain matin dans [le numéro #139](http://redisweekly.com/archive/139.html)

**Comment by guillaumef** [comment]
Merci.
Heureux de croiser un autre entrepreneur FR dans ces contrées technologiques ;-)
Bonne continuation à vous.
