### ISSUE TITLE
src/eredis.c:202: error: redefinition of typedef ‘eredis_reader_t’

### ISSUE THREAD

**Issue by djshafran** [EulerianTechnologies/eredis#2]
Hello!

> [root@gerasim eredis]# make
> [ 20%] Built target hiredis-inc
> [ 40%] Built target hiredis-src
> [ 50%] Building C object src/CMakeFiles/eredis.dir/eredis.c.o
> /tmp/c/redis/eredis/src/eredis.c:202: error: redefinition of typedef ‘eredis_reader_t’
> /tmp/c/redis/eredis/include/eredis.h:59: note: previous declaration of ‘eredis_reader_t’ was here
> /tmp/c/redis/eredis/src/eredis.c:238: error: redefinition of typedef ‘eredis_t’
> /tmp/c/redis/eredis/include/eredis.h:58: note: previous declaration of ‘eredis_t’ was here
> make[2]: **\* [src/CMakeFiles/eredis.dir/eredis.c.o] Error 1
> make[1]: **\* [src/CMakeFiles/eredis.dir/all] Error 2
> make: **\* [all] Error 2

Please tell how it can be compiled? Or i'm doing something wrong?

**Comment by guillaumef** [comment]
Hi,
Not sure which c compiler and version you are using. Build test is automated with current stable gcc/clang and is all good.
This redefinition 'error' should be a warning at most. Recent compilers are allowing this trick silently.
Despite this, i have dropped the redefinition. You can 'git pull' and retry.
Regards,
Guillaume

**Comment by djshafran** [comment]
yep... i'm using CentOS... so installing gcc 4.6.3 solved this question

**Comment by djshafran** [comment]
if it is possible to solve, would be amazing!

if i put code from init section to client.c file and put all this into eredis source directory, and try to build, have this:
[root@gerasim eredis]# gcc client.c -o client -I./include
client.c:3:1: error: initializer element is not constant
client.c:6:20: error: expected ‘)’ before numeric constant
client.c:9:18: error: expected ‘)’ before numeric constant
client.c:12:20: error: expected ‘)’ before numeric constant

**Comment by guillaumef** [comment]
It is C. You have to integrate the init code in a C code structure, you must have at least an "int main(void) {}".
Check the associated examples.
Bye.

**Comment by djshafran** [comment]
Oh. Thank you so much!

**Comment by djshafran** [comment]
Amazing speed.... 140kop/s.... Fantastic... No Comments... They are not possible
