### ISSUE TITLE
eredis, timeout command

### ISSUE THREAD

**Issue by limbo127** [EulerianTechnologies/eredis#5]
Before using eredis for multi thread operation, we are using hiredis.
however, as the issue : https://github.com/redis/hiredis/issues/306  , 
we need to use the hiredis timeout branch : https://github.com/redis/hiredis/tree/with-timeout 
to avoid redis command pending.

How can we do, we eredis, our first tests seems to show us the same problem, sometime , redis command blocks and not release.

Regards, 
Nicolas Prochazka

**Comment by guillaumef** [comment]
I never reach this problem. You can try it with the branch by editing src/CMakeLists.txt, replace line 9 with:
`
  COMMAND git clone -b with-timeout https://github.com/redis/hiredis.git
`

'make distclean' and rebuild it.

Tell me if it is doing the job for your timeout problem, in this case, i will study further what is the purpose of this branch and perhaps integrate it by default in the build.
Thanks.

Regards,
Guillaume

**Comment by limbo127** [comment]
Ok thanks.
this hiredis branch causes some other troubles, so no not integrate it.
Regards, Nicolas
