### ISSUE TITLE
NOAUTH Authentication required even after executing auth command

### ISSUE THREAD

**Issue by cogmeta** [EulerianTechnologies/eredis#9]
eredis client is sometimes returning "NOAUTH Authentication required" error even after setting auth via AUTH command. To be clear, some commands appear to succeed before the error returns.  Anyone has any explanation?

**Comment by guillaumef** [comment]
I think you reached the timeout of your redis connection (server side) and the reconnect (which is seamless) is not reapplying the AUTH command.
I will test it and let you known. Thanks (sorry for the delay).

**Comment by guillaumef** [comment]
Patched here: https://github.com/EulerianTechnologies/eredis/commit/b25cc1b9c4191df9b540efbbb8ed955965af15ef

Take a look at 'eredis_pc_cmd' here: https://github.com/EulerianTechnologies/eredis#add-post-connection-requests-beta

Please let me know if it's ok for you.

**Comment by cogmeta** [comment]
Thank,  @guillaumef.  I will test eredis_pc_cmd and report back.
